server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialiect: org.hibernate.dialect.MySQL8Dialect
# you can put your custom global variables here
app:
  security:
    jwt:
      secret: "put-your-jwt-secret-here"
      duration: 86400 # a day
      issuer: "WhoYouAre"
